### ISSUE TITLE
Why is this a public template?

### ISSUE THREAD

**Issue by ardasevinc** [Elodream/awesome-python-hosting#1]
Hello. This repo should not be marked as "Public template". 
Public templates are used for generating a copy repo (not forking!)

I propose removing that from the repo settings.

**Comment by ngdream** [comment]
> Hello. This repo should not be marked as "Public template". Public templates are used for generating a copy repo (not forking!)
> 
> I propose removing that from the repo settings.

thanks for your suggestion
